<a href="https://colab.research.google.com/github/DiomedesIguax/BootCampTaller1/blob/17032024Titanic/Titanic2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **APRENDIZAJE SUPERVISADO**

In [5]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

**ANALISIS EXPLORATORIO**

In [6]:
titanic= sns.load_dataset('titanic')
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

**TIPOS DE DATOS**

In [7]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [10]:
titanic.dropna(inplace=True)

In [24]:
 #Seleccionar características y etiquetas
x = titanic[['pclass', 'sex', 'age']]
y = titanic['survived']

# Convertir la variable 'sex' a numérica
x['sex'] = x['sex'].map({'male': 0, 'female': 1})

# Dividir los datos en conjuntos de entrenamiento y prueba
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

# Crear y entrenar el modelo de regresión logística
model = LogisticRegression()
model.fit(x_train, y_train)

# Realizar predicciones
predictions = model.predict(x_test)

<ipython-input-24-fb6e05ec6fd7>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x['sex'] = x['sex'].map({'male': 0, 'female': 1})

In [28]:
# Calcular y mostrar la precisión del modelo
print("______________________________________________________________________________")
print("Accuracy:", accuracy_score(y_test, predictions))
print("______________________________________________________________________________")
print('\n\033[1mConfusion Matrix:\033[0m')
print(confusion_matrix(y_test, predictions))
print("______________________________________________________________________________")
print("______________________________________________________________________________")
print('\n\033[1mClassification Report:\033[0m')
print(classification_report(y_test, predictions))
print("______________________________________________________________________________")

______________________________________________________________________________
Accuracy: 0.7297297297297297
______________________________________________________________________________

Confusion Matrix:
[[ 9  4]
 [ 6 18]]
______________________________________________________________________________
______________________________________________________________________________

Classification Report:
              precision    recall  f1-score   support

           0       0.60      0.69      0.64        13
           1       0.82      0.75      0.78        24

    accuracy                           0.73        37
   macro avg       0.71      0.72      0.71        37
weighted avg       0.74      0.73      0.73        37

______________________________________________________________________________